CREATE TABLE IF NOT EXISTS members (
    member_id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    phone_number VARCHAR(40) NOT NULL
);

ALTER TABLE transactions
    ADD COLUMN IF NOT EXISTS fine_amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00;
